### ISSUE TITLE
Extra whitespace in between sections

### ISSUE THREAD

**Issue by qubist** [holochain/website#62]
It seems there's extra whitespace created by Jekyll in between a few sections on the homepage:

The "Holochain helps people" and "Holochain apps help" sections:
<img width="1440" alt="screen shot 2018-04-09 at 4 54 22 pm" src="https://user-images.githubusercontent.com/3607279/38522507-d1ff5272-3c16-11e8-8d8b-ecd112dad561.png">

The "Low-cost, lightweight, secure" and "Start building your own innovative applications" sections:
<img width="1440" alt="screen shot 2018-04-09 at 4 54 27 pm" src="https://user-images.githubusercontent.com/3607279/38522527-e4ab9494-3c16-11e8-9a67-7e66c7ca241d.png">

**Comment by bboyatwork** [comment]
Dunno if you saw my recent comment addressing this @qubist, but with how the front page looks now I was suggested the whitespace actually allows the page to breath more rather than trying to force the images to touch there. We could try a different image lay out too tho. Any thoughts @celestialhanley ?

**Comment by qubist** [comment]
All good, just saw the change and didn't know if it was intentional. 👍
